version: '3.9'

services:
  doc_retriever_qdrant:
    build:
      context: .
      dockerfile: Dockerfile
    image: doc_retriever_qdrant
    environment:
      - OPEN_AOI_KEY=<opean_ai_key>
      - USERNAME_APRA=<username_apra>
      - PASSWORD=<password_apra>
      - INTERVAL=<doc_retriever_interval>
      - PDF_HOST=<host_base_url>
    ports: 
      - 8502:8502
    volumes: 
      - ./app/PDFs:/app/PDFs

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant-data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO  

volumes:
  qdrant-data:
    driver: local #to create the storage in the local file system (the virtual one)